// ─────────────────────────────────────────────────────────────
//  캐릭터 도트 v2 (48x48 프레임, 약 40px 키 · 3등신)
//  역할 문자 → 디자인의 colors로 팔레트 이름에 매핑.
//   O 외곽선  S/s 피부  k 볼  E 눈동자  e 홍채  w 눈 하이라이트  X 입
//   H/h/I 머리카락  C/c 주 옷감  M/m 보조 옷감  D 어두운 안감  T/t 장식(금속)
//   A/a/W 갑옷  L/l 가죽  P/p 바지  B/b 부츠  K/k 망토/스카프  R/r 강조색  G/g 보석  Q/q 방패
//  모두 왼쪽(적 방향)을 바라보는 3/4 시점.
// ─────────────────────────────────────────────────────────────
export const FRAME2 = { w: 48, h: 48 };
export const ANIMS2 = [
  { name: 'idle', fps: 5, loop: true },
  { name: 'walk', fps: 9, loop: true },
  { name: 'attack', fps: 18, loop: false, hit: 3 },
  { name: 'cast', fps: 8, loop: false, hit: 2 },
  { name: 'hurt', fps: 10, loop: false },
  { name: 'guard', fps: 1, loop: true },
  { name: 'victory', fps: 4, loop: true },
  { name: 'ko', fps: 1, loop: true },
];

// 기본 부착 위치 (프레임 좌표, 파츠 그리드의 왼쪽 위)
export const ANCHORS2 = {
  head: [16, 7], torso: [17, 22], legs: [17, 35],
  shoulderF: [21.5, 24.5], shoulderB: [27.5, 24.5],
  cape: [26, 22], tail: [28, 11],
};
export const ARM2 = { pivot: { x: 3, y: 1.5 }, hand: 7.5 };

export const HEADS2 = {
  leon: [
    '......O.....O...',
    '.....OHO...OIO..',
    '...O.OHIO.OHHO..',
    '..OHOHIHHOHIHHO.',
    '.OHIHHHHHHHHHHhO',
    '.OHHHHHHHHHHHhhO',
    'ORRRRRRRRRRRRrrO',
    'OHHSHHHSHHHHhhhO',
    'OHSSSHSSSSHHhhO.',
    'OSOOSSSOOOSShhO.',
    'OSEwSSSEewSSjhO.',
    'OSeeSSSEeeSShSO.',
    'OjSSSSSSSSjSSsO.',
    '.OSSSSXXSSSSssO.',
    '..OSSSSSSSssOO..',
    '...OOOOOOOOO....',
  ],
  sera: [
    '....OOOOOO......',
    '..OOCCCCCCOO....',
    '.OCCCCCCCCCCO...',
    'OCCCCCCCCCCccO..',
    'OCCCCCCCCCCcccO.',
    'OTTTTTTTTTCcccO.',
    'OHHIHHHHHTCcccO.',
    'OHSHHSSHHTCcccO.',
    'OSSSSSSSSTCcccO.',
    'OSOOSSOOOSTccccO',
    'OSEwSSEewSTcccO.',
    'OSeeSSEeeSTcccO.',
    'OjSSSSSSjSTcccO.',
    '.OSSSXSSSSTccO..',
    '..OSSSSSSOTcO...',
    '...OOOOOO.OO....',
  ],
  bran: [
    '......OOO.......',
    '.....ORRRO......',
    '....ORRRrRO.....',
    '..OOOOORrOOOO...',
    '.OAAWAAAAAAAaO..',
    'OAWAAAAAAAAAaaO.',
    'OAAAAAAAAAAAaaO.',
    'OTTTTTTTTTTTaaO.',
    'OAOOOAOOOOAaaaO.',
    'OSEwSASEwSOaaO..',
    'OSSSSASSSSOaaO..',
    'OHHHSSSHHHOaO...',
    'OHHHHXHHHHHOO...',
    '.OHhHHHHHhHO....',
    '..OHhHHHhHO.....',
    '...OOOOOOO......',
  ],
  kyle: [
    '....O.O.O.......',
    '...OIOIOIO.O....',
    '..OHIHHIHHOIO...',
    '.OHHhHHHhHHHHO..',
    'OHIHHhHHHhHHHhO.',
    'OHHhHHHhHHHhHhhO',
    'OhHHHhHHHHhHhhhO',
    'OHHHHHHSHHHHhhO.',
    'OHHHHHSSSSHHhhO.',
    'OHHHHSSOOOSShhO.',
    'OhHHHSSEewSShhO.',
    '.OhHSSSEeeSShhO.',
    '.OHSSSSSSSjShO..',
    '..OSSSSXSSSShO..',
    '..OOSSSSSSSOO...',
    '....OOOOOOO.....',
  ],
  rhea: [
    '............OO..',
    '..........OOWO..',
    '....OOOOOOAWO...',
    '..OOAAWWAAAAO...',
    '.OAAWAAAAAAAaO..',
    'OAWAAAAAAAAAaaO.',
    'OAAATTTTTTAAaaO.',
    'OAOOOOOOOOAAaaO.',
    'OHHSHHSSHHOAaaO.',
    'OSOOSSOOOSOAaO..',
    'OSEwSSEewSOAaO..',
    'OSeeSSEeeSOaO...',
    'OjSSSSSSjSOaO...',
    '.OSSSXSSSSOO....',
    '..OSSSSSSOO.....',
    '...OOOOOO.......',
  ],
  bun: [
    '......OOOO......',
    '.....OHHIHO.....',
    '.....OHHHhO.....',
    '...OOOOHHOOOO...',
    '..OHHIHHHHHHhO..',
    '.OHHHHHHHHHHhhO.',
    'OHHHHHHHHHHHhhhO',
    'OHHSHHHSSHHHhhhO',
    'OHSSSSSSSSHHhhO.',
    'OSOOSSSOOOSShhO.',
    'OSEwSSSEewSShhO.',
    'OSeeSSSEeeSSShO.',
    'OjSSSSSSSSjSShO.',
    '.OSSSSXSSSSSOO..',
    '..OSSSSSSSOO....',
    '...OOOOOOO......',
  ],
  beard: [
    '................',
    '....OOOOOO......',
    '..OOSSWSSSOO....',
    '.OSSWSSSSSSsO...',
    '.OSSSSSSSSSssO..',
    'OSSSSSSSSSSssO..',
    'OSSSSSSSSSHhhO..',
    'OHHHSSHHHSSHhhO.',
    'OSOOSSSOOOSSShO.',
    'OSEwSSSEwSSSkhO.',
    'OSSSSSSSSSSSShO.',
    'OHHHHSSHHHHSSO..',
    'OHHHHHHHHHHHO...',
    '.OHHhHHHHhHHO...',
    '..OHHhHHhHHO....',
    '...OHHhHHhO.....',
  ],
};

// 몸통 (기본 14폭; 넓은 것은 x 오프셋 지정)
export const TORSOS2 = {
  jacket: { grid: [
    '..OKKKKKKKKO..',
    '.OKKjKKKKjjKO.',
    'OCCOKKKKKOCCcO',
    'OCCMOKjKOMCCcO',
    'OCCMMOKOMMCCcO',
    'OCcCMMOMMMCCcO',
    'OCcCMMMMMMCccO',
    'OLLLLLTLLLLllO',
    'OCcCMMMMMMCccO',
    'OCcCCMMMMCCccO',
    'OCcCCOOOOCCccO',
    '.OcCO....OCcO.',
    '..OO......OO..',
  ] },
  robe: { dx: -1, grid: [
    '...OOCCCCCCOO...',
    '..OCCCCCCCCccO..',
    '.OCCCCTTTCCcccO.',
    '.OCCCCTGTCCcccO.',
    '.OCCMMOTOMMcccO.',
    '.OCCMMMMMMMcccO.',
    '.OCCMMMMMMMcccO.',
    '.OTTTTTTTTTTttO.',
    '.OCCMMMMMMMcccO.',
    '.OCCCMMMMMCcccO.',
    '.OCCCMMMMMCcccO.',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OCCCCMMMMMCccccO',
    'OTTTTMMMMMTttttO',
    'OTTTTOOOOOTttttO',
    '.OOOO.....OOOO..',
  ] },
  plate: { dx: -1, grid: [
    '.OOOO....OOOO...',
    'OAWAAO..OAWAaO..',
    'OAAAAaOOAAAAaO..',
    'OaAAaORRROaAaaO.',
    '.OaaORRRRROaaO..',
    '.OAAORRTRRRAaaO.',
    '.OAAORRTRRRAaaO.',
    '.OLLLLLTLLLLllO.',
    '.OAAORRRRRRAaaO.',
    '.OAaORRRRRrAaaO.',
    '.OAaORRRRRrAaO..',
    '.OaaOORRRrrOaO..',
    '..OO.ORRrrO.OO..',
    '......OOOO......',
  ] },
  coat: { grid: [
    '..OCCO..OCCO..',
    '..OCCCOOCCCO..',
    '.OCCCDDDDCCcO.',
    'OCCCODDDDOCccO',
    'OCCCTODDOCCccO',
    'OCCCCTDDOCCccO',
    'OCCCCTDDCCcccO',
    'OLLLLLTLLLLllO',
    'OCCCCTCCCCcccO',
    'OCCCCCCCCCcccO',
    'OCCCCCCCCCcccO',
    'OCCcCO..OCCccO',
    'OCcCO....OCcO.',
    'OOOO......OO..',
  ] },
  scale: { grid: [
    '..OOOOOOOO....',
    '.OAWAAAAWAaO..',
    'OAWWAAAAAAaaO.',
    'OAAAAAAAAAaaO.',
    'OAaAaAaAaAaaO.',
    'OAAAAAAAAAaaO.',
    'OAaAaATaAaaaO.',
    'OLLLLLTLLLLlO.',
    'OCCCCCCCCCccO.',
    'OCCcCCCCcCccO.',
    'OCcCCcCCCcCcO.',
    '.OCcO..OCccO..',
    '..OO....OOO...',
  ] },
};

// 다리 (14x12, y=35)
export const LEGS2 = {
  stand: [
    '..OPPPPPPPPO..',
    '..OPPPpOPPpO..',
    '..OPPpO.OPpO..',
    '..OPPpO.OPpO..',
    '..OPPpO.OPpO..',
    '..OPPpO.OPpO..',
    '..OBBBO.OBBO..',
    '..OBBbO.OBbO..',
    '..OBBbO.OBbO..',
    '.OBBBbO.OBbO..',
    'OBBBBbO.OBBbO.',
    'OOOOOOO.OOOOO.',
  ],
  walk1: [
    '..OPPPPPPPPO..',
    '..OPPPpOPPpO..',
    '.OPPpO..OPpO..',
    '.OPPpO...OPpO.',
    'OPPpO....OPpO.',
    'OPPpO.....OPpO',
    'OBBBO.....OBBO',
    'OBBbO.....OBbO',
    'OBBbO.....OBbO',
    'OBBbO....OBBbO',
    'OBBBbO...OBBbO',
    'OOOOOO...OOOOO',
  ],
  walk2: [
    '...OPPPPPPO...',
    '...OPPPpPPO...',
    '...OPPpOPpO...',
    '....OPpOPpO...',
    '....OPpOPpO...',
    '....OPpOPpO...',
    '....OBBOBBO...',
    '....OBbOBbO...',
    '....OBbOBbO...',
    '...OBBbOBbO...',
    '..OBBBbOBBbO..',
    '..OOOOOOOOOO..',
  ],
  lunge: [
    '..OPPPPPPPPO..',
    '.OPPPpOOOPPpO.',
    '.OPPpO...OPPpO',
    'OPPpO.....OPpO',
    'OPPpO.....OPpO',
    'OPpO.......OpO',
    'OBBO.......OBO',
    'OBbO.......OBO',
    'OBbO......OBbO',
    'OBbO......OBbO',
    'OBBbO.....OBBO',
    'OOOOO.....OOOO',
  ],
  feet: [
    '..............', '..............', '..............', '..............', '..............',
    '..............', '..............', '..............', '..............', '..............',
    '.OBBBOOBBbO...',
    '.OOOOO.OOOO...',
  ],
  feetStep: [
    '..............', '..............', '..............', '..............', '..............',
    '..............', '..............', '..............', '..............', '..............',
    'OBBBO...OBBbO.',
    'OOOOO...OOOOO.',
  ],
};
export const LEGSETS2 = {
  boots: { stand: 'stand', walk1: 'walk1', walk2: 'walk2', lunge: 'lunge' },
  robe: { stand: 'feet', walk1: 'feetStep', walk2: 'feet', lunge: 'feetStep' },
};

// 팔 (피벗 3,1.5 → 손은 7.5px 아래)
export const ARMS2 = {
  cloth: [
    '.OOOO.',
    'OCCCcO',
    'OCCCcO',
    '.OCCcO',
    '.OCCcO',
    '.OCCcO',
    '.OTTtO',
    '.OLLlO',
    'OLLLlO',
    'OLLLlO',
    '.OOOO.',
  ],
  sleeve: [
    '.OOOO..',
    'OCCCcO.',
    'OCCCcO.',
    'OCCCccO',
    'OCCCccO',
    'OCCCccO',
    'OTTTttO',
    '.OSSsO.',
    '.OSSsO.',
    '.OSSsO.',
    '..OOO..',
  ],
  armor: [
    'OOOOO.',
    'OAWAaO',
    'OAAAaO',
    '.OAaO.',
    '.OAaO.',
    '.OAaO.',
    'OAWAaO',
    'OAAAaO',
    'OAAAaO',
    'OAAAaO',
    '.OOOO.',
  ],
};

// 흔들리는 파츠: cape(몸 뒤), tail(머리 뒤/앞). 프레임 배열
export const SWAY2 = {
  scarf: [
    ['OOO.....', 'OKKOO...', '.OKjKOO.', '..OKjjKO', '...OKjKO', '...OKjO.', '....OKO.', '....OO..'],
    ['OOOO....', 'OKKKOOO.', '.OKjjKKO', '..OOKjjO', '....OKO.', '.....O..'],
    ['OO......', 'OKO.....', 'OKjO....', '.OKjO...', '.OKjO...', '..OKjO..', '..OKjO..', '...OKO..', '...OO...'],
  ],
  ribbon: [
    ['OO....', 'ORrO..', '.ORrO.', '..ORrO', '...OrO', '....O.'],
    ['OO....', 'ORrOO.', '.ORRrO', '..OOrO', '....O.'],
    ['OO....', 'ORO...', 'ORrO..', '.ORrO.', '.ORrO.', '..OO..'],
  ],
  braid: [
    ['.OO.', 'OHIO', 'OHhO', '.OHO', 'OHIO', 'OHhO', '.OHO', 'OHIO', '.OTO', '..O.'],
    ['.OO.', 'OHIO', 'OHhO', '.OHO', 'OHIO', 'OHhO', 'OHO.', 'OHIO', 'OTO.', '.O..'],
    ['.OO.', 'OHIO', 'OHhO', '.OHO', '.OHIO', '.OHhO', '..OHO', '.OHIO', '.OTO.', '..O..'],
  ],
  plume: [
    ['OOO.....', 'ORRROO..', '.OrRRRO.', '..OOrrRO', '....OOrO', '......O.'],
    ['OOO.....', 'ORRROOO.', '.OrRRRRO', '..OOOrrO', '.....OO.'],
    ['OOO.....', 'ORRRO...', '.OrRRO..', '..OrRRO.', '...OrrO.', '....OO..'],
  ],
  ponytail: [
    ['OO......', 'OHHOO...', '.OHHhOO.', '..OHHhhO', '...OHhhO', '...OHhO.', '....OhO.', '....OhO.', '.....O..'],
    ['OO......', 'OHHOOO..', '.OHHHhOO', '..OOHhhO', '....OHhO', '.....OhO', '......O.'],
    ['OO......', 'OHHO....', 'OHHhO...', '.OHHhO..', '.OHHhO..', '..OHhO..', '..OHhO..', '...OhO..', '...OO...'],
  ],
  coattail: [
    ['OOOO....', 'OCCcO...', 'OCCccO..', 'OCCccO..', '.OCcccO.', '.OCcccO.', '..OCccO.', '..OCccO.', '...OOO..'],
    ['OOOO....', 'OCCcOO..', '.OCCccOO', '.OCCcccO', '..OCCccO', '...OCcO.', '....OO..'],
    ['OOOO....', 'OCCcO...', 'OCCcO...', 'OCCccO..', 'OCCccO..', 'OCCccO..', '.OCccO..', '.OCccO..', '..OOO...'],
  ],
  cape: [
    ['OOOOO...', 'OKKKkO..', 'OKKKkO..', 'OKKKkkO.', 'OKKKkkO.', '.OKKkkO.', '.OKKkkO.', '..OKkkO.', '..OOOO..'],
    ['OOOOO...', 'OKKKkOO.', 'OKKKKkkO', '.OKKKkkO', '..OKKkkO', '...OKkO.', '....OO..'],
    ['OOOOO...', 'OKKKkO..', 'OKKKkO..', 'OKKKkO..', 'OKKKkkO.', 'OKKKkkO.', 'OKKKkkO.', '.OKKkkO.', '.OOOOOO.'],
  ],
  beard: [
    ['.OHHHO', 'OHHhHO', 'OHHhO.', '.OHHO.', '..OO..'],
    ['.OHHHO', 'OHHhHO', '.OHHhO', '..OHO.', '...O..'],
    ['.OHHHO', 'OHHhHO', 'OHHhO.', 'OHHO..', '.OO...'],
  ],
};

export const SHIELD2 = { x: 9, y: 25, grid: [
  'OOOOOOOOOOOO',
  'OQQQQTTQQQqO',
  'OQWQQTTQQQqO',
  'OQQQQTTQQQqO',
  'OTTTTTTTTTtO',
  'OQQQQTTQQQqO',
  'OQQQQTTQQqqO',
  '.OQQQTTQQqO.',
  '.OQQQTTQQqO.',
  '..OQQTTQqO..',
  '..OQQTTqqO..',
  '...OQTTqO...',
  '....OTtO....',
  '.....OO.....',
] };

// 무기 (날이 위, grip = 손잡이 중심)
export const WEAPONS2 = {
  sword: { grip: { x: 3.5, y: 16 }, grid: [
    '...OO...',
    '..OWbO..', '..OWbO..', '..OWbO..', '..OWbO..', '..OWbO..', '..OWbO..',
    '..OWbO..', '..OWbO..', '..OWbO..', '..OWbO..', '..OWbO..', '..OWbO..',
    'OTTTGTTO',
    'OOTTTTOO',
    '..OLlO..', '..OLlO..', '..OLlO..',
    '..OTTO..',
    '...OO...',
  ] },
  greatsword: { grip: { x: 4.5, y: 24 }, grid: [
    '....OO....',
    '...OWBO...',
    '..OWWBbO..',
    '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..',
    '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..',
    '..OWBBbO..', '..OWBBbO..', '..OWBBbO..', '..OWBBbO..',
    '.OTTTTTTO.',
    'OTTGGGGTTO',
    '.OTTTTTTO.',
    '...OLlO...', '...OLlO...', '...OLlO...', '...OLlO...', '...OLlO...',
    '...OTTO...',
    '....OO....',
  ] },
  spear: { grip: { x: 2.5, y: 21 }, grid: [
    '..O..',
    '.OWO.',
    '.OWO.',
    'OWWbO',
    'OWBbO',
    'OWBbO',
    '.OBO.',
    '.OBO.',
    'OTGTO',
    'OTTTO',
    '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.',
    '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.',
    '.OTO.',
    '..O..',
  ] },
  staff: { grip: { x: 3.5, y: 16 }, grid: [
    '..OOOO..',
    '.OTTTTO.',
    'OTOOOOTO',
    'OTOWGOTO',
    'OTOGgOTO',
    '.OTOOTO.',
    '..OTTO..',
    '...OO...',
    '...OLO..', '...OLO..', '...OLO..', '...OLO..', '...OLO..', '...OLO..', '...OLO..',
    '...OLO..', '...OLO..', '...OLO..', '...OLO..', '...OLO..', '...OLO..', '...OLO..',
    '...OTO..',
    '....O...',
  ] },
  rod: { grip: { x: 2.5, y: 10 }, grid: [
    '..O..',
    '.OGO.',
    'OGWgO',
    'OGGgO',
    '.OgO.',
    '.OTO.',
    'OTTTO',
    '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.', '.OLO.',
    '.OTO.',
    '..O..',
  ] },
};

// 포즈 (b: 몸 이동, h: 머리 추가 이동, fa/ba: 앞/뒷팔 각도, w: 무기 각도, sw: 흔들림 프레임)
export const POSES2 = {
  idle: [
    { fa: 22, ba: -14, w: 140, sw: 0 },
    { fa: 22, ba: -14, w: 140, sw: 0 },
    { b: [0, 1], fa: 18, ba: -10, w: 137, sw: 1 },
    { b: [0, 1], fa: 18, ba: -10, w: 137, sw: 1 },
  ],
  walk: [
    { legs: 'walk1', fa: 45, ba: -40, w: 145, sw: 1 },
    { b: [0, -1], fa: 18, ba: -12, w: 145, sw: 0 },
    { legs: 'walk2', fa: -12, ba: 22, w: 160, sw: 2 },
    { b: [0, -1], fa: 18, ba: -12, w: 145, sw: 0 },
  ],
  attack_slash: [
    { b: [3, 1], fa: 205, ba: -40, w: 220, sw: 2 },
    { b: [4, 0], fa: 222, ba: -48, w: 240, sw: 2 },
    { b: [-2, 1], legs: 'lunge', fa: 125, ba: -55, w: 110, sw: 1 },
    { b: [-5, 2], legs: 'lunge', fa: 58, ba: -62, w: 40, sw: 1 },
    { b: [-5, 2], legs: 'lunge', fa: 48, ba: -62, w: 30, sw: 1 },
    { b: [-2, 0], fa: 25, ba: -20, w: 120, sw: 0 },
  ],
  attack_thrust: [
    { b: [3, 0], fa: 65, ba: -25, w: 100, sw: 2 },
    { b: [5, 1], fa: 60, ba: -30, w: 98, sw: 2 },
    { b: [-3, 0], legs: 'lunge', fa: 88, ba: -45, w: 90, sw: 1 },
    { b: [-7, 0], legs: 'lunge', fa: 92, ba: -50, w: 90, sw: 1 },
    { b: [-7, 0], legs: 'lunge', fa: 92, ba: -50, w: 90, sw: 1 },
    { b: [-2, 0], fa: 40, ba: -20, w: 130, sw: 0 },
  ],
  cast: [
    { fa: 120, ba: 40, w: 165, sw: 0 },
    { b: [0, -1], fa: 165, ba: 150, w: 180, glow: true, sw: 1 },
    { b: [0, -1], fa: 170, ba: 158, w: 182, glow: true, sw: 1 },
  ],
  hurt: [
    { b: [4, 0], h: [1, 1], fa: -30, ba: -50, w: 225, sw: 2 },
    { b: [3, 1], h: [1, 1], fa: -20, ba: -40, w: 210, sw: 2 },
  ],
  guard: [
    { b: [1, 1], legs: 'lunge', fa: 95, ba: 60, w: 178, sw: 0 },
  ],
  victory: [
    { b: [0, -1], fa: 175, ba: -25, w: 182, sw: 1 },
    { fa: 168, ba: -20, w: 178, sw: 2 },
  ],
  ko: [
    { b: [3, 1], h: [1, 1], fa: -20, ba: -40, w: 210, ko: true, sw: 2 },
  ],
};

const BASE = { O: 'ink', S: 'skin', s: 'skinS', k: 'skinD', E: 'eye', w: 'white', X: 'redS' };
// 디자인: head/torso/legs/arm/sway 파츠 + 색
export const DESIGNS2 = {
  leon: { head: 'leon', torso: 'jacket', legs: 'boots', arm: 'cloth', cape: 'scarf', tail: 'ribbon', tailAt: [13, 5],
    colors: { ...BASE, e: 'blueS', H: 'hairBrown', h: 'hairBrownS', I: 'hairBrownL', R: 'red', r: 'redS', C: 'blue', c: 'blueS', M: 'creamL', m: 'cream', K: 'red', j: 'redS', T: 'gold', t: 'goldS', L: 'leather', l: 'leatherS', P: 'pants', p: 'pantsS', B: 'leather', b: 'leatherS' } },
  sera: { head: 'sera', torso: 'robe', legs: 'robe', arm: 'sleeve', tail: 'braid', tailAt: [2, 13], tailFront: true,
    colors: { ...BASE, e: 'teal', H: 'hairGold', h: 'hairGoldS', I: 'hairGoldL', C: 'creamL', c: 'cream', M: 'blue', m: 'blueS', T: 'gold', t: 'goldS', G: 'crystal', g: 'crystalS', L: 'leather', l: 'leatherS', B: 'leatherS', b: 'ink' } },
  bran: { head: 'bran', torso: 'plate', legs: 'boots', arm: 'armor', tail: 'plume', tailAt: [9, 0], shield: true,
    colors: { ...BASE, e: 'eye', H: 'hairBrown', h: 'hairBrownS', A: 'steel', a: 'steelS', W: 'steelL', T: 'gold', t: 'goldS', R: 'red', r: 'redS', L: 'leather', l: 'leatherS', P: 'steelS', p: 'darkMetal', B: 'darkMetal', b: 'darkMetalS', Q: 'blue', q: 'blueS' } },
  kyle: { head: 'kyle', torso: 'coat', legs: 'boots', arm: 'cloth', cape: 'coattail', capeAt: [26, 29],
    colors: { ...BASE, e: 'red', H: 'hairSilver', h: 'hairSilverS', I: 'hairSilverL', C: 'crimson', c: 'crimsonS', D: 'darkMetalS', T: 'gold', t: 'goldS', L: 'darkMetal', l: 'darkMetalS', P: 'darkMetal', p: 'darkMetalS', B: 'ink', b: 'darkMetalS' } },
  rhea: { head: 'rhea', torso: 'scale', legs: 'boots', arm: 'armor', cape: 'cape', tail: 'ponytail', tailAt: [11, 7],
    colors: { ...BASE, e: 'teal', H: 'hairRed', h: 'hairRedS', I: 'hairRedL', A: 'teal', a: 'tealS', W: 'tealL', T: 'gold', t: 'goldS', C: 'tealS', c: 'darkMetal', K: 'red', j: 'redS', L: 'leather', l: 'leatherS', P: 'tealS', p: 'darkMetal', B: 'teal', b: 'tealS' } },
  // NPC
  elder: { head: 'beard', torso: 'robe', legs: 'robe', arm: 'sleeve', tail: 'beard', tailAt: [3, 14], tailFront: true,
    colors: { ...BASE, H: 'hairSilverL', h: 'hairSilverS', W: 'creamL', C: 'green', c: 'greenS', M: 'cream', m: 'creamS', T: 'gold', t: 'goldS', G: 'crystal', g: 'crystalS', B: 'leatherS', b: 'ink' } },
  merchant: { head: 'leon', torso: 'jacket', legs: 'boots', arm: 'cloth',
    colors: { ...BASE, e: 'leather', H: 'hairGold', h: 'hairGoldS', I: 'hairGoldL', R: 'green', r: 'greenS', C: 'green', c: 'greenS', M: 'cream', m: 'creamS', K: 'gold', j: 'goldS', T: 'gold', t: 'goldS', L: 'leather', l: 'leatherS', P: 'leatherS', p: 'ink', B: 'leather', b: 'leatherS' } },
  innkeeper: { head: 'bun', torso: 'robe', legs: 'robe', arm: 'sleeve',
    colors: { ...BASE, e: 'green', H: 'hairRed', h: 'hairRedS', I: 'hairRedL', C: 'red', c: 'redS', M: 'creamL', m: 'cream', T: 'creamL', t: 'cream', G: 'red', g: 'redS', B: 'leatherS', b: 'ink' } },
  clerk: { head: 'bun', torso: 'coat', legs: 'boots', arm: 'cloth',
    colors: { ...BASE, e: 'purple', H: 'hairNavy', h: 'hairNavyS', I: 'hairNavyL', C: 'purple', c: 'purpleS', D: 'creamL', T: 'gold', t: 'goldS', L: 'purpleS', l: 'ink', P: 'pants', p: 'pantsS', B: 'ink', b: 'ink' } },
  herbalist: { head: 'sera', torso: 'robe', legs: 'robe', arm: 'sleeve',
    colors: { ...BASE, e: 'green', H: 'hairBrown', h: 'hairBrownS', I: 'hairBrownL', C: 'mossL', c: 'moss', M: 'cream', m: 'creamS', T: 'flowerPink', t: 'magentaS', G: 'flowerPink', g: 'magentaS', B: 'leatherS', b: 'ink' } },
  kid: { head: 'leon', torso: 'jacket', legs: 'boots', arm: 'cloth', cape: 'scarf',
    colors: { ...BASE, e: 'blue', H: 'hairGold', h: 'hairGoldS', I: 'hairGoldL', R: 'hairGold', r: 'hairGoldS', C: 'red', c: 'redS', M: 'creamL', m: 'cream', K: 'gold', j: 'goldS', T: 'gold', t: 'goldS', L: 'leather', l: 'leatherS', P: 'pants', p: 'pantsS', B: 'leather', b: 'leatherS' } },
};
