// UI 아이콘 도트 데이터. 각 아이콘 = grid + colors(역할→팔레트 이름)
const O = 'ink';
export const ICONS = {
  cursor: { colors: { O, W: 'white', S: 'creamS' }, grid: [
    '..OOOOO.........',
    '.OWWWWWOOOOOOOO.',
    'OWWWWWWWWWWWWWWO',
    'OWWWWWOOOOOOOOO.',
    'OWWWWWWWO.......',
    'OWWWWSOO........',
    'OWWWWWWWO.......',
    '.OSWWSOO........',
    '..OOOOO.........',
  ] },
  fire: { colors: { O, F: 'fireS', Y: 'fire', W: 'fireL' }, grid: [
    '....O.....',
    '...OFO....',
    '...OFFO...',
    '..OFFFO.O.',
    '..OFFYFOFO',
    '.OFFYYFFFO',
    '.OFYYWYFFO',
    '.OFYWWYFO.',
    '..OFYYFO..',
    '...OOOO...',
  ] },
  ice: { colors: { O, I: 'ice', W: 'iceL', s: 'iceS' }, grid: [
    '....OO....',
    '...OIWO...',
    '..OIWIIO..',
    '.OIWIIIIO.',
    'OIWIIIIIsO',
    'OIIIIIIssO',
    '.OIIIIIsO.',
    '..OIIIsO..',
    '...OIsO...',
    '....OO....',
  ] },
  bolt: { colors: { O, Y: 'bolt', W: 'boltL' }, grid: [
    '....OOOO..',
    '...OYWYO..',
    '...OYYO...',
    '..OYYO....',
    '..OYWOOOO.',
    '.OYYYYWYO.',
    '..OOOYYO..',
    '....OYO...',
    '...OYO....',
    '...OO.....',
  ] },
  wind: { colors: { O, G: 'wind', W: 'windL' }, grid: [
    '..........',
    '.OOOOOO...',
    'OWGGGGGO..',
    '.OOOOOGGO.',
    'OOOO..OGO.',
    'WGGGOOGGO.',
    'OOOOGGGO..',
    '...OOOO...',
    '.OOOOO....',
    'OGGGGGO...',
  ] },
  light: { colors: { O, Y: 'light', W: 'white', S: 'lightS' }, grid: [
    '....OO....',
    '....OYO...',
    '...OYYO...',
    'OOOOYYOOOO',
    'OYYYWWYYSO',
    '.OOYWWYOO.',
    '..OYYYSO..',
    '..OYOOSO..',
    '.OYO..OSO.',
    '.OO....OO.',
  ] },
  dark: { colors: { O, D: 'dark', d: 'darkS', W: 'darkL' }, grid: [
    '...OOOO...',
    '..OWDDDO..',
    '.OWDDOO...',
    'ODDDO.....',
    'ODDdO.....',
    'ODDdO.....',
    'ODDddO....',
    '.ODDddOOO.',
    '..ODDDddO.',
    '...OOOOO..',
  ] },
  slash: { colors: { O, W: 'steelL', T: 'gold', L: 'leather' }, grid: [
    '........OO',
    '.......OWO',
    '......OWO.',
    '.....OWO..',
    '....OWO...',
    '.O.OWO....',
    'OTOWO.....',
    '.OTO......',
    'OLOTO.....',
    'OO.O......',
  ] },
  pierce: { colors: { O, W: 'steelL', L: 'wood' }, grid: [
    '......OOOO',
    '.......OWO',
    '......OWWO',
    '.....OWOOO',
    '....OLO...',
    '...OLO....',
    '..OLO.....',
    '.OLO......',
    'OOO.......',
    '..........',
  ] },
  strike: { colors: { O, S: 'steel', W: 'steelL', L: 'wood' }, grid: [
    '..OOOO....',
    '.OWSSSO...',
    'OWSSSSSO..',
    'OSSSSSSO..',
    '.OSSOSO...',
    '..OOLO....',
    '....OLO...',
    '.....OLO..',
    '......OLO.',
    '.......OO.',
  ] },
  potion: { colors: { O, R: 'red', s: 'redS', W: 'white', C: 'wood' }, grid: [
    '...OOO....',
    '...OCO....',
    '..OOOOO...',
    '.ORRRRRO..',
    'ORRWRRRRO.',
    'ORWRRRRRO.',
    'ORRRRRRRO.',
    'ORRRRRRsO.',
    '.OssssssO.',
    '..OOOOOO..',
  ] },
  ether: { base: 'potion', colors: { O, R: 'blue', s: 'blueS', W: 'white', C: 'wood' } },
  hipotion: { base: 'potion', colors: { O, R: 'magenta', s: 'magentaS', W: 'white', C: 'gold' } },
  feather: { colors: { O, F: 'fireL', f: 'fire', W: 'white' }, grid: [
    '.......OO.',
    '......OWFO',
    '.....OWFFO',
    '....OWFFfO',
    '...OWFFfO.',
    '..OWFFfO..',
    '..OFFfO...',
    '.OOffO....',
    'OO.OO.....',
    'O.........',
  ] },
  herb: { colors: { O, G: 'green', g: 'greenS', W: 'greenL', P: 'flowerPink' }, grid: [
    '...OO.....',
    '..OPPO.OO.',
    '..OPPOOWGO',
    '...OOOWGgO',
    '.OO.OGGgO.',
    'OWGOOGgO..',
    'OGGgOgO...',
    '.OgggGO...',
    '...OOgO...',
    '.....OO...',
  ] },
  shard: { colors: { O, C: 'crystal', c: 'crystalS', W: 'crystalL' }, grid: [
    '....OO....',
    '...OWCO...',
    '...OWCO...',
    '..OWCCcO..',
    '..OWCCcO..',
    '..OCCCcO..',
    '..OCCccO..',
    '...OCcO...',
    '...OCcO...',
    '....OO....',
  ] },
  armor: { colors: { O, A: 'steel', a: 'steelS', W: 'steelL', T: 'gold' }, grid: [
    '.OO....OO.',
    'OAAOOOOAaO',
    'OWAATTAAaO',
    'OAWAATAAaO',
    '.OAAATAaO.',
    '.OAAATAaO.',
    '.OAAAAAaO.',
    '.OaAAAAaO.',
    '..OaaaaO..',
    '...OOOO...',
  ] },
  ring: { colors: { O, G: 'gold', g: 'goldS', C: 'crystal', W: 'white' }, grid: [
    '...OOOO...',
    '..OCWCCO..',
    '...OCCO...',
    '..OGOOGO..',
    '.OGO..OgO.',
    'OGO....OgO',
    'OGO....OgO',
    '.OgO..OgO.',
    '..OggggO..',
    '...OOOO...',
  ] },
  active: { colors: { O, Y: 'gold', W: 'goldL', s: 'goldS' }, grid: [
    '....OO....',
    '...OWYO...',
    'OOOOWYOOOO',
    'OWWWYYYYsO',
    '.OYYYYYsO.',
    '..OYYYsO..',
    '..OYOOYO..',
    '.OYO..OsO.',
    '.OO....OO.',
    '..........',
  ] },
  passive: { colors: { O, C: 'crystal', c: 'crystalS', W: 'crystalL' }, grid: [
    '...OOOO...',
    '..OWWCCO..',
    '.OWCCCCcO.',
    'OWCCCCCCcO',
    'OCCCCCCccO',
    '.OCCCCccO.',
    '..OCCccO..',
    '...OccO...',
    '....OO....',
    '..........',
  ] },
  gold: { colors: { O, G: 'gold', g: 'goldS', W: 'goldL' }, grid: [
    '..OOOOO...',
    '.OWWGGGO..',
    'OWGGgGGgO.',
    'OGGgGGGgO.',
    'OGGgGGGgO.',
    'OGGgGGGgO.',
    '.OGGGGgO..',
    '..OOOOO...',
    '..........',
    '..........',
  ] },
  chest: { colors: { O, W: 'wood', w: 'woodS', G: 'gold', L: 'woodL' }, grid: [
    '.OOOOOOOO.',
    'OLLLLLLLwO',
    'OLWWWWWWwO',
    'OOOOGGOOOO',
    'OWWWGGWWwO',
    'OWWWWWWWwO',
    'OwwwwwwwwO',
    'OOOOOOOOOO',
    '..........',
    '..........',
  ] },
  heart: { colors: { O, R: 'red', W: 'redL', s: 'redS' }, grid: [
    '.OO...OO..',
    'OWRO.ORRO.',
    'OWRRORRRsO',
    'ORRRRRRRsO',
    '.ORRRRRsO.',
    '..ORRRsO..',
    '...ORsO...',
    '....OO....',
    '..........',
    '..........',
  ] },
  star: { colors: { O, Y: 'bolt', W: 'boltL' }, grid: [
    '....OO....',
    '...OYYO...',
    'OOOOYWOOOO',
    'OYYYWWYYYO',
    '.OYYYYYYO.',
    '..OYYYYO..',
    '..OYOOYO..',
    '.OYO..OYO.',
    '.OO....OO.',
    '..........',
  ] },
  lock: { colors: { O, G: 'goldS', S: 'steel', W: 'steelL' }, grid: [
    '..OOOOO...',
    '.OSOOOSO..',
    '.OSO.OSO..',
    'OOOOOOOOO.',
    'OGGGGGGGO.',
    'OGGGOGGGO.',
    'OGGGOGGGO.',
    'OGGGGGGGO.',
    'OOOOOOOOO.',
    '..........',
  ] },
  unknown: { colors: { O, W: 'steelL', s: 'steelS' }, grid: [
    '..OOOOO...',
    '.OWWWWWO..',
    'OWWOOOWWO.',
    'OOO..OWWO.',
    '....OWWO..',
    '...OWWO...',
    '...OWsO...',
    '...OOOO...',
    '...OWWO...',
    '...OOOO...',
  ] },
};
