// ─────────────────────────────────────────────────────────────
//  도트 데이터 (순수 데이터 — 생성 로직은 generate.js)
//  각 그리드의 문자는 "역할(role)"이고, 실제 색은 디자인의 colors
//  매핑 → PALETTE 이름으로 결정된다. '.'은 투명.
//  공통 역할: O 외곽선(ink)
// ─────────────────────────────────────────────────────────────

// 캐릭터 프레임 규격 (외부 스프라이트 시트로 교체할 때도 이 규격을 따른다)
export const CHAR_FRAME = { w: 32, h: 32 };
export const CHAR_ANIMS = [ // 시트의 행 순서
  { name: 'idle', fps: 4, loop: true },
  { name: 'walk', fps: 8, loop: true },
  { name: 'attack', fps: 16, loop: false, hit: 2 },
  { name: 'cast', fps: 8, loop: false, hit: 2 },
  { name: 'hurt', fps: 10, loop: false },
  { name: 'guard', fps: 1, loop: true },
  { name: 'victory', fps: 4, loop: true },
  { name: 'ko', fps: 1, loop: true },
];

// ── 머리 (12x12, 왼쪽을 바라봄) ──
export const HEADS = {
  short: [
    '...OOOOO....',
    '..OHHHHHOO..',
    '.OHIIHHHHHO.',
    'OHHHHHHHHHhO',
    'OHHHHHHHHhhO',
    'OHSHHSHHHhhO',
    'OSSSSSSSHhhO',
    'OSESSESSShhO',
    'OSESSESSSSsO',
    '.OSSSSSSSsO.',
    '..OSsSSSsO..',
    '...OOOOOO...',
  ],
  long: [
    '...OOOOOO...',
    '..OHHIIHHO..',
    '.OHIHHHHHHO.',
    'OHHHHHHHHHhO',
    'OHTGTTTTHhhO',
    'OHSHSSHHHhhO',
    'OSSSSSSSHhhO',
    'OSESSESSHhhO',
    'OSESSESSSHhO',
    '.OSSSSSSSHhO',
    '..OSSSSSOHhO',
    '...OOOOOOhO.',
  ],
  spiky: [
    '..O.O.OO....',
    '.OHOHOHHO...',
    '.OHHHHHIHO..',
    'OHHHHHHHHHO.',
    'OHHHHHHHHHhO',
    'OHHSHHHSHhhO',
    'OSSSSSSSHhhO',
    'OSESSESSShhO',
    'OSESSESSSSsO',
    '.OSSSSSSSsO.',
    '..OSsSSSsO..',
    '...OOOOOO...',
  ],
  dragoon: [
    '........OO..',
    '...OOOOOAO..',
    '..OAAWAAAaO.',
    '.OAWAAAAAAaO',
    'OAAAAAAAAaaO',
    'OAOOOOOOAaaO',
    'OASSSSSSOaaO',
    'OSESSESSOaaO',
    'OSESSESSOAaO',
    '.OSSSSSSOaHO',
    '..OSsSSSOOHO',
    '...OOOOOO.O.',
  ],
  knight: [
    '.....OOO....',
    '....OKKKO...',
    '..OOOKKOOO..',
    '.OAAWAAAAaO.',
    'OAWAAAAAAaaO',
    'OTTTTTTTTaaO',
    'OSSSSSSSOaaO',
    'OSESSESSOaaO',
    'OSESSESSOaaO',
    '.OSSSSSSOaO.',
    '..OSsSSSOO..',
    '...OOOOOO...',
  ],
  bun: [ // NPC: 올림머리
    '....OOOO....',
    '...OHHIHO...',
    '...OHHHhO...',
    '..OOHHHhOO..',
    '.OHHHHHHHhO.',
    'OHHHHHHHHhhO',
    'OHSSHSSHHhhO',
    'OSSSSSSSHhhO',
    'OSESSESSShhO',
    'OSESSESSSSsO',
    '.OSSSSSSSsO.',
    '..OOOOOOOO..',
  ],
  bald: [ // NPC: 촌장 (대머리+수염)
    '...OOOOOO...',
    '..OSSWSSSO..',
    '.OSWSSSSSsO.',
    'OSSSSSSSSssO',
    'OSSSSSSSSHhO',
    'OHHSSHHSSHhO',
    'OSSSSSSSSHhO',
    'OSESSESSSshO',
    'OSESSESSSSsO',
    'OHHHHHHHHsO.',
    '.OHHHHHHhO..',
    '..OOHHHOO...',
  ],
};

// ── 몸통 (시작 위치 x=11 기준 10폭, robe는 x=10 기준 12폭) ──
export const TORSOS = {
  tunic: { x: 11, y: 17, grid: [
    '..OOOOOO..',
    '.OCCCCCcO.',
    'OCCTCCCCcO',
    'OCCTCCCCcO',
    'OCCTCCCccO',
    'OLLLLLLLlO',
    'OCCCCCCccO',
    '.OOOOOOOO.',
  ] },
  coat: { x: 11, y: 17, grid: [
    '..OOOOOO..',
    '.ODCCCCDO.',
    'OCDCCCCDcO',
    'OCCDCCCccO',
    'OCCCDCCccO',
    'OLLLLLLLlO',
    'OCCcOCCccO',
    'OCcO.OCcO.',
  ] },
  robe: { x: 10, y: 17, grid: [
    '...OOOOOOHO.',
    '..OCCCCCOHO.',
    '.OCCTCCCcHO.',
    '.OCCTCCCcHO.',
    '.OCCTCCCchO.',
    '.OTTTTTTTTO.',
    '.OCCTCCCccO.',
    '.OCCTCCCccO.',
    'OCCCTCCCcccO',
    'OCCCTCCCcccO',
    'OCCCTCCCcccO',
    'OcccTcccccOO',
    '.OOOOOOOOOO.',
  ] },
  armor: { x: 11, y: 17, grid: [
    '..OOOOOO..',
    '.OAWAAAaO.',
    'OAWAAAAaaO',
    'OAAATAAaaO',
    'OaAATAAaaO',
    'OLLLLLLLlO',
    'OAaAAAaAaO',
    '.OOOOOOOO.',
  ] },
};

// ── 다리 (x=11, y=25, 10x7) ──
export const LEGS = {
  stand: [
    '..OPPPPPO.',
    '..OPPOPpO.',
    '..OPPOPpO.',
    '..OPPOPpO.',
    '..OLLOLlO.',
    '.OLLLOLLlO',
    '.OOOOOOOOO',
  ],
  walk1: [
    '..OPPPPPO.',
    '.OPPOOPpO.',
    '.OPPO.OpO.',
    'OPPO..OpO.',
    'OLLO..OLO.',
    'OLLLO.OLlO',
    'OOOOO.OOOO',
  ],
  walk2: [
    '..OPPPPO..',
    '...OPPpO..',
    '...OPPpO..',
    '...OPPpO..',
    '...OLLlO..',
    '..OLLLlO..',
    '..OOOOOO..',
  ],
  lunge: [
    '..OPPPPPO.',
    '.OPPOOOPpO',
    'OPPO...OpO',
    'OPO....OpO',
    'OLO....OLO',
    'OLLLO..OLO',
    'OOOOO..OOO',
  ],
  feetStand: [
    '..........', '..........', '..........', '..........', '..........',
    '.OLLOOLlO.',
    '.OOOO.OOO.',
  ],
  feetStep: [
    '..........', '..........', '..........', '..........', '..........',
    'OLLO..OLlO',
    'OOOO..OOOO',
  ],
};
export const LEG_SETS = {
  normal: { stand: 'stand', walk1: 'walk1', walk2: 'walk2', lunge: 'lunge' },
  robe: { stand: 'feetStand', walk1: 'feetStep', walk2: 'feetStand', lunge: 'feetStep' },
};

// ── 팔 (피벗 = (1.5, 1), 손 = 피벗에서 5px) ──
export const ARMS = {
  cloth: ['.OO.', 'OCcO', 'OCcO', 'OCcO', 'OSsO', 'OSsO', '.OO.'],
  armor: ['OOOO', 'OAWO', 'OAaO', 'OAaO', 'OSsO', 'OSsO', '.OO.'],
};
export const ARM_PIVOT = { x: 1.5, y: 1 };
export const SHOULDER = { front: { x: 14.5, y: 19 }, back: { x: 19.5, y: 19 } };

// ── 무기 (날이 위를 향함, grip = 손이 쥐는 지점) ──
// 역할: W 하이라이트, b 날 그림자, B 날, T 가드(금속), L 손잡이, G 보석, g 보석 그림자
export const WEAPON_SHAPES = {
  sword: { grip: { x: 2.5, y: 9.5 }, grid: [
    '..OO..',
    '.OWbO.',
    '.OWbO.',
    '.OWbO.',
    '.OWbO.',
    '.OWbO.',
    '.OWbO.',
    '.OWbO.',
    'OTGTTO',
    '.OLLO.',
    '.OLLO.',
    '..OO..',
  ] },
  greatsword: { grip: { x: 3.5, y: 15.5 }, grid: [
    '...OO...',
    '..OWBO..',
    '.OWWBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    '.OWBBbO.',
    'OTTGGTTO',
    'OOTTTTOO',
    '..OLLO..',
    '..OLLO..',
    '..OLLO..',
    '...OO...',
  ] },
  spear: { grip: { x: 2.5, y: 15.5 }, grid: [
    '..O..',
    '.OWO.',
    '.OWO.',
    'OWBbO',
    'OWBbO',
    '.OBO.',
    'OTGTO',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '..O..',
  ] },
  staff: { grip: { x: 2.5, y: 11.5 }, grid: [
    '.OOO.',
    'OGWgO',
    'OGGgO',
    '.OOO.',
    'OTOTO',
    '.OTO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '..O..',
  ] },
  rod: { grip: { x: 2.5, y: 7.5 }, grid: [
    '..O..',
    '.OGO.',
    'OGWgO',
    '.OgO.',
    '.OTO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '.OLO.',
    '..O..',
  ] },
};
// 무기 종류별 기본 색 (무기 아이템이 tint로 덮어쓸 수 있음)
export const WEAPON_COLORS = {
  sword: { O: 'ink', W: 'steelL', b: 'steel', B: 'steel', T: 'gold', G: 'crystal', g: 'crystalS', L: 'leather' },
  greatsword: { O: 'ink', W: 'steelL', b: 'steelS', B: 'steel', T: 'darkMetal', G: 'red', g: 'redS', L: 'leather' },
  spear: { O: 'ink', W: 'steelL', b: 'steelS', B: 'steel', T: 'gold', G: 'crystal', g: 'crystalS', L: 'wood' },
  staff: { O: 'ink', W: 'crystalL', G: 'crystal', g: 'crystalS', T: 'gold', L: 'wood', B: 'steel', b: 'steelS' },
  rod: { O: 'ink', W: 'magentaL', G: 'magenta', g: 'magentaS', T: 'gold', L: 'darkMetal', B: 'steel', b: 'steelS' },
};
// 공격 모션 계열
export const WEAPON_STYLE = { sword: 'slash', greatsword: 'slash', spear: 'thrust', staff: 'slash', rod: 'slash' };

export const SHIELD = { x: 8, y: 18, grid: [
  'OOOOOOO',
  'OAWAAaO',
  'OWTTTaO',
  'OATGTaO',
  'OATTTaO',
  'OAAAAaO',
  '.OAAaO.',
  '..OaO..',
  '...O...',
] };

// ── 포즈 (angle: 0=아래, 90=앞(왼쪽), 180=위) ──
// b: 상체 이동, h: 머리 추가 이동, fa/ba: 앞/뒤 팔, w: 무기 날 방향
export const POSES = {
  idle: [
    { fa: 25, ba: -15, w: 150 },
    { fa: 25, ba: -15, w: 150 },
    { b: [0, 1], fa: 21, ba: -11, w: 147 },
    { b: [0, 1], fa: 21, ba: -11, w: 147 },
  ],
  walk: [
    { legs: 'walk1', fa: 45, ba: -35, w: 150 },
    { b: [0, -1], fa: 20, ba: -10, w: 150 },
    { legs: 'walk2', fa: -5, ba: 15, w: 165 },
    { b: [0, -1], fa: 20, ba: -10, w: 150 },
  ],
  attack_slash: [
    { b: [2, 0], fa: 200, ba: -30, w: 215 },
    { b: [-1, 0], legs: 'lunge', fa: 135, ba: -40, w: 140 },
    { b: [-3, 1], legs: 'lunge', fa: 62, ba: -50, w: 62 },
    { b: [-3, 1], legs: 'lunge', fa: 55, ba: -50, w: 50 },
    { b: [-1, 0], fa: 30, ba: -20, w: 125 },
  ],
  attack_thrust: [
    { b: [2, 0], fa: 60, ba: -20, w: 100 },
    { b: [1, 0], fa: 70, ba: -25, w: 95 },
    { b: [-4, 0], legs: 'lunge', fa: 90, ba: -40, w: 90 },
    { b: [-4, 0], legs: 'lunge', fa: 90, ba: -40, w: 90 },
    { b: [-1, 0], fa: 40, ba: -20, w: 130 },
  ],
  cast: [
    { fa: 120, ba: 40, w: 165 },
    { b: [0, -1], fa: 160, ba: 150, w: 180, glow: true },
    { b: [0, -1], fa: 165, ba: 158, w: 182, glow: true },
  ],
  hurt: [
    { b: [3, 0], h: [1, 1], fa: -30, ba: -50, w: 225, flash: true },
    { b: [2, 1], h: [1, 1], fa: -20, ba: -40, w: 210 },
  ],
  guard: [
    { b: [1, 1], legs: 'lunge', fa: 95, ba: 60, w: 178 },
  ],
  victory: [
    { b: [0, -1], fa: 175, ba: -25, w: 182 },
    { fa: 168, ba: -20, w: 178 },
  ],
  ko: [
    { b: [2, 1], h: [1, 1], fa: -20, ba: -40, w: 210, ko: true },
  ],
};

// ── 캐릭터 / NPC 디자인 ──
const BASE = { O: 'ink', S: 'skin', s: 'skinS', E: 'eye', L: 'leather', l: 'leatherS', P: 'pants', p: 'pantsS' };
export const CHAR_DESIGNS = {
  leon: { head: 'short', torso: 'tunic', legs: 'normal', arm: 'cloth',
    colors: { ...BASE, H: 'hairBrown', h: 'hairBrownS', I: 'hairBrownL', C: 'blue', c: 'blueS', T: 'gold' } },
  sera: { head: 'long', torso: 'robe', legs: 'robe', arm: 'cloth',
    colors: { ...BASE, H: 'hairGold', h: 'hairGoldS', I: 'hairGoldL', C: 'cream', c: 'creamS', T: 'teal', G: 'crystal' } },
  kyle: { head: 'spiky', torso: 'coat', legs: 'normal', arm: 'cloth',
    colors: { ...BASE, H: 'hairNavy', h: 'hairNavyS', I: 'hairNavyL', C: 'crimson', c: 'crimsonS', D: 'gold', P: 'darkMetal', p: 'darkMetalS' } },
  rhea: { head: 'dragoon', torso: 'armor', legs: 'normal', arm: 'armor',
    colors: { ...BASE, H: 'hairRed', A: 'teal', a: 'tealS', W: 'tealL', T: 'gold', P: 'tealS', p: 'darkMetalS' } },
  bran: { head: 'knight', torso: 'armor', legs: 'normal', arm: 'armor', shield: true,
    colors: { ...BASE, A: 'steel', a: 'steelS', W: 'steelL', T: 'gold', K: 'red', G: 'red', P: 'steelS', p: 'darkMetal' } },
  // NPC
  elder: { head: 'bald', torso: 'robe', legs: 'robe', arm: 'cloth',
    colors: { ...BASE, H: 'hairSilver', h: 'hairSilverS', W: 'white', C: 'green', c: 'greenS', T: 'gold' } },
  merchant: { head: 'short', torso: 'tunic', legs: 'normal', arm: 'cloth',
    colors: { ...BASE, H: 'hairGold', h: 'hairGoldS', I: 'hairGoldL', C: 'green', c: 'greenS', T: 'cream' } },
  innkeeper: { head: 'bun', torso: 'robe', legs: 'robe', arm: 'cloth',
    colors: { ...BASE, H: 'hairRed', h: 'hairRedS', I: 'hairRedL', C: 'red', c: 'redS', T: 'cream' } },
  clerk: { head: 'bun', torso: 'coat', legs: 'normal', arm: 'cloth',
    colors: { ...BASE, H: 'hairNavy', h: 'hairNavyS', I: 'hairNavyL', C: 'purple', c: 'purpleS', D: 'gold' } },
  herbalist: { head: 'long', torso: 'robe', legs: 'robe', arm: 'cloth',
    colors: { ...BASE, H: 'hairBrown', h: 'hairBrownS', I: 'hairBrownL', C: 'green', c: 'greenS', T: 'cream', G: 'flowerPink' } },
  kid: { head: 'spiky', torso: 'tunic', legs: 'normal', arm: 'cloth',
    colors: { ...BASE, H: 'hairGold', h: 'hairGoldS', I: 'hairGoldL', C: 'red', c: 'redS', T: 'cream' } },
};

// ─────────────────────────────────────────────────────────────
//  몬스터 (오른쪽=파티 방향을 바라봄). mirror:true면 왼쪽 절반만 그리고 대칭 복사.
// ─────────────────────────────────────────────────────────────
export const MONSTER_SHAPES = {
  slime: { grid: [
    '......OOOO......',
    '....OOBBBBOO....',
    '...OBBWWBBBBO...',
    '..OBBWWBBBBBBO..',
    '..OBBBBBBBBBBO..',
    '.OBBBBBBBBBBBbO.',
    '.OBBBBBBEBBBEbO.',
    'OBBBBBBBEBBBEbbO',
    'OBBBBBBBBBBBBbbO',
    'OBBBBBBBBBMMBbbO',
    'OBBBBBBBBBBBbbbO',
    '.ObBBBBBBBBbbbO.',
    '..OObbbbbbbbOO..',
    '....OOOOOOOO....',
  ] },
  rabbit: { grid: [
    '..OO.OO...........',
    '.OBOOBbO..........',
    '.OBbOBbO......O...',
    '..OBbOBbO....OWO..',
    '...OBBBBOOOOOWO...',
    '...OBBBBBBBBBOO...',
    '..OBBBBBBBBBBBBO..',
    '..OBBBBBBBBBBEBO..',
    '.OBBBBBBBBBBBBBBO.',
    '.OBWWBBBBBBBBBNBO.',
    '.OBWWWBBBBBBBBBO..',
    '..OBWWBBBBBBBbO...',
    '..ObbbObbbbObbO...',
    '...OOO.OOOO.OOO...',
  ] },
  mushroom: { grid: [
    '.....OOOOOO.....',
    '...OOBBBBBBOO...',
    '..OBBWWBBBBBBO..',
    '.OBBWWBBBWWBBBO.',
    '.OBBBBBBBWWBBBO.',
    'OBBWWBBBBBBBBBbO',
    'OBBWWBBBBBWWBbbO',
    'ObBBBBBBBBWWbbbO',
    '.ObbbbbbbbbbbbO.',
    '..OOOOOOOOOOOO..',
    '...OSSSSSSSSO...',
    '...OSSSSESSESO..',
    '...OSSSSESSESO..',
    '...OSSSSSSSSsO..',
    '...OsSSSSSSSsO..',
    '....OssssssO....',
    '...OLLO..OLLO...',
    '...OOOO..OOOO...',
  ] },
  wolf: { grid: [
    '................O..O....',
    '...............OBOOBO...',
    '...............OBBBBBO..',
    '..............OBBBBEBBO.',
    '..............OBBBBBBBBO',
    'OO...........OBBBBBBWWNO',
    'OBO.........OBBBBBBWWOO.',
    '.OBO.OOOOOOOBBBBBBWWO...',
    '.OBBOBBBBBBBBBBBBBWO....',
    '..OBBBBBBBBBBBBBBBBO....',
    '..OBBBBBBBBBBBBBBBbO....',
    '...ObBBBBBBBBBBBBbbO....',
    '...ObbOObbbbbbOObbO.....',
    '...ObO.ObO..ObO.ObO.....',
    '...ObO.ObO..ObO.ObO.....',
    '...OOO.OOO..OOO.OOO.....',
  ] },
  bat: { mirror: true, grid: [
    'O.......O.',
    'OO......OB',
    'OBO....OBB',
    'OBBO..OBEB',
    'OBBBOOBBBB',
    'OBWBBOBBBB',
    'OBBWBBOBBB',
    'OBBBWBOBBB',
    '.OBBBBOOBM',
    '..OBBO..OO',
    '...OO.....',
  ] },
  wisp: { mirror: true, grid: [
    '......O',
    '.....OB',
    '..O..OB',
    '.OBO.OB',
    '.OBBOBB',
    'OBBBBBW',
    'OBBBBWW',
    'OBBWWWW',
    'OBBWEWW',
    'OBBWEWW',
    'OBBWWWW',
    '.OBBWWW',
    '.OBBBWW',
    '..OBBBB',
    '...OBBB',
    '....OOb',
    '......O',
  ] },
  golem: { mirror: true, grid: [
    '..............',
    '..........OOOO',
    '.........OBBBB',
    '........OBWBBB',
    '........OBBBBB',
    '........OBEEBB',
    '........OBBBBB',
    '...OOOOOOObbbb',
    '..OCCOBBBBOOOO',
    '.OCCWCOBBBBBBB',
    '.OCWCCOBBBBBBB',
    '.OCCCCOBBBBGBB',
    '..OOOOBBBBBBBB',
    '..OBBObBBBBBBB',
    '.OBBBObBBBBBBB',
    '.OBBBOObbbbbbb',
    '.OBBBO.OOOOOOO',
    '.OBBBO.OBBBBBB',
    'OBBBBBO.ObBBBB',
    'OBBWBBO.ObBBBB',
    'OBBBBBO.ObbBBB',
    '.OOOOO..ObbBBO',
    '........ObbBO.',
    '.......OBBBBO.',
    '.......OOOOOO.',
  ] },
  treant: { mirror: true, grid: [
    '.........OOOOOO',
    '.......OOLLLLLL',
    '.....OOLLlLLLLL',
    '....OLLLLLLLLlL',
    '...OLLlLLLLLLLL',
    '..OLLLLLLlLLLLL',
    '..OLlLLLLLLLLlL',
    '.OLLLLLlLLLLLLL',
    '.OLLLLLLLLLLLLL',
    '.OlLLlLLLLlLLLL',
    '..OllOLLlLLLLLL',
    '...OOObOOllLLlL',
    '..OBO.OBbOOllll',
    '.OBO..OBBBOOOOO',
    'OBO...OBBBBBBBB',
    'OBBO..OBbBBBBBB',
    '.OBO..ObBOOBBBB',
    '..OBO.OBOEEOBBB',
    '...OBOOBBOOBBBB',
    '....OBOBBBBBBBB',
    '.....OBBbBBBBBB',
    '......OBBOOOOOO',
    '......OBBOMMMMM',
    '......OBBBOOOOO',
    '......ObBBBBBBB',
    '......ObBBBbBBB',
    '.....OBbBBBBBBB',
    '....OBBOBbBBOBB',
    '...OBBO.ObBO.OB',
    '..OBBO..OBO...O',
    '..OOO...OOO....',
  ] },
  dragon: { mirror: true, grid: [
    '........................',
    '................O.......',
    '................OO......',
    '.................OCO....',
    '.................OCCO.OO',
    'O.................OCCOBB',
    'OO.................OBBBB',
    'OWO...............OBBBBB',
    'OWWO..............OBEEBB',
    'OCWWO.............OBBBBW',
    'OCCWWO.............OBBBB',
    'OCCCWWO............OBMBM',
    'OCCCCWWO...........OOBBB',
    'OCCKCCWWO..........OBBBB',
    '.OCKCCCWWO........OOBBBB',
    '.OCCKCCCWWO......OBBBBBB',
    '.OCCCKCCCWWO....OBBBBBWB',
    '..OCCCKCCCWWOOOOBBBBBWBB',
    '..OCCCCKCCCWWBBBBBBBBWBB',
    '..OCCCCCKCCCOBBBBBBBBBGG',
    '...OCCCCCKCCOBBBBBBBBBGG',
    '...OCCCCCCKCOBBBBBBBBBBB',
    '....OCCCCCCKOBBBBBBBBbbb',
    '....OOCCOCCOObBBBBBBBbbb',
    '.....O.OO.OO.ObBBBBBbbbb',
    '..............ObBBBBbbbb',
    '..............ObbBBBbbbb',
    '...............ObbBbbOOO',
    '..............OBBObbO...',
    '.............OBBBOObO...',
    '.............OBBBO.OO...',
    '............OBBBO.......',
    '............OWOWO.......',
    '............OOOOO.......',
  ] },
};

// 몬스터 외형 = 모양 + 색 매핑 (팔레트 스왑으로 변종 생성)
export const MONSTER_DESIGNS = {
  slime: { shape: 'slime', colors: { O: 'ink', B: 'grassL', b: 'grass', W: 'white', E: 'eye', M: 'grassD' } },
  slimeIce: { shape: 'slime', colors: { O: 'ink', B: 'ice', b: 'iceS', W: 'white', E: 'eye', M: 'iceS' } },
  rabbit: { shape: 'rabbit', colors: { O: 'ink', B: 'cream', b: 'creamS', W: 'white', E: 'eye', N: 'flowerPink' } },
  mushroom: { shape: 'mushroom', colors: { O: 'ink', B: 'red', b: 'redS', W: 'cream', S: 'cream', s: 'creamS', E: 'eye', L: 'leather' } },
  mushroomP: { shape: 'mushroom', colors: { O: 'ink', B: 'purple', b: 'purpleS', W: 'flowerYellow', S: 'cream', s: 'creamS', E: 'eye', L: 'leather' } },
  wolf: { shape: 'wolf', colors: { O: 'ink', B: 'stone', b: 'stoneS', W: 'white', E: 'fireL', N: 'ink' } },
  bat: { shape: 'bat', colors: { O: 'ink', B: 'purple', b: 'purpleS', W: 'crystal', E: 'fireL', M: 'white' } },
  wisp: { shape: 'wisp', colors: { O: 'fireS', B: 'fire', b: 'fireS', W: 'fireL', E: 'ink' } },
  golem: { shape: 'golem', colors: { O: 'ink', B: 'caveRockL', b: 'caveRock', W: 'crystalL', E: 'crystalL', C: 'crystal', G: 'magenta' } },
  treant: { shape: 'treant', colors: { O: 'ink', L: 'moss', l: 'mossS', B: 'wood', b: 'woodS', E: 'fireL', M: 'ink' } },
  dragon: { shape: 'dragon', colors: { O: 'ink', B: 'crystal', b: 'crystalS', W: 'crystalL', C: 'iceS', K: 'steelL', E: 'magentaL', M: 'ink', G: 'magenta' } },
  dragonDark: { shape: 'dragon', colors: { O: 'black', B: 'dark', b: 'darkS', W: 'darkL', C: 'magentaS', K: 'magentaL', E: 'fireL', M: 'black', G: 'fire' } },
};

export const MONSTER_ANIMS = [
  { name: 'idle', fps: 4, loop: true },
  { name: 'attack', fps: 12, loop: false, hit: 2 },
  { name: 'cast', fps: 8, loop: false, hit: 2 },
  { name: 'hurt', fps: 10, loop: false },
];
