// 지형/오브젝트 텍스처 레시피 (데이터). generate.js의 makeTexture가 해석한다.
// fill: 바탕색, noise: [[색, 확률]...], pattern: 무늬 종류, sprinkle: 작은 장식
export const TILE_SIZE = 16;
export const TILE_RECIPES = {
  grass: { fill: 'grass', noise: [['grassS', 0.16], ['grassL', 0.1]], sprinkle: [{ shape: 'blade', color: 'grassL', shade: 'grassS', count: 5 }] },
  grassFlower: { base: 'grass', sprinkle: [
    { shape: 'blade', color: 'grassL', shade: 'grassS', count: 3 },
    { shape: 'flower', color: 'flowerPink', count: 2 },
    { shape: 'flower', color: 'flowerYellow', count: 1 },
    { shape: 'flower', color: 'flowerWhite', count: 1 }] },
  grassSide: { fill: 'dirtS', noise: [['dirt', 0.2], ['leatherS', 0.1]], pattern: 'grassEdge', edge: ['grass', 'grassS'] },
  dirt: { fill: 'dirt', noise: [['dirtS', 0.18], ['dirtL', 0.12]], sprinkle: [{ shape: 'pebble', color: 'stoneL', shade: 'stoneS', count: 2 }] },
  sand: { fill: 'sand', noise: [['sandS', 0.15], ['white', 0.04]] },
  stoneFloor: { fill: 'stone', pattern: 'tiles', cell: 8, mortar: 'stoneS', shades: ['stone', 'stoneL', 'stone'], noise: [['stoneS', 0.06]] },
  stoneWall: { fill: 'stone', pattern: 'bricks', bw: 8, bh: 4, mortar: 'stoneD', shades: ['stone', 'stoneL', 'stoneS'], noise: [['stoneS', 0.05]] },
  mossWall: { base: 'stoneWall', noise: [['moss', 0.12], ['mossS', 0.06]] },
  plaster: { fill: 'plaster', noise: [['plasterS', 0.08]], pattern: 'timber', beam: 'woodS' },
  planks: { fill: 'wood', pattern: 'planks', ph: 4, line: 'woodS', shades: ['wood', 'woodL', 'wood'] },
  roofRed: { fill: 'roofRed', pattern: 'shingles', line: 'roofRedS', hi: 'redL' },
  roofBlue: { fill: 'roofBlue', pattern: 'shingles', line: 'roofBlueS', hi: 'blueL' },
  leaves: { fill: 'green', noise: [['greenS', 0.3], ['greenL', 0.14], ['grassD', 0.08]], pattern: 'blobs', hi: 'greenL' },
  leavesDark: { fill: 'moss', noise: [['mossS', 0.3], ['green', 0.12], ['grassD', 0.12]], pattern: 'blobs', hi: 'green' },
  bark: { fill: 'wood', pattern: 'vstripes', line: 'woodS', noise: [['woodL', 0.08]] },
  water: { fill: 'water', noise: [['waterS', 0.15]], pattern: 'waves', hi: 'waterL' },
  caveFloor: { fill: 'caveRock', noise: [['caveRockS', 0.12], ['caveRockL', 0.06]], sprinkle: [{ shape: 'pebble', color: 'caveRockL', shade: 'caveRockS', count: 3 }] },
  caveTop: { fill: 'caveRockL', noise: [['caveRock', 0.25], ['crystalS', 0.03]] },
  caveWall: { fill: 'caveRock', pattern: 'rocks', line: 'caveRockS', hi: 'caveRockL', noise: [['caveRockS', 0.1]], sprinkle: [{ shape: 'speck', color: 'crystal', count: 2 }] },
  crystal: { fill: 'crystal', pattern: 'facets', line: 'crystalS', hi: 'crystalL' },
  darkCrystal: { fill: 'dark', pattern: 'facets', line: 'darkS', hi: 'magentaL' },
  altar: { fill: 'stoneL', pattern: 'tiles', cell: 16, mortar: 'stoneS', shades: ['stoneL', 'stone'], sprinkle: [{ shape: 'rune', color: 'crystal', count: 1 }] },

  // ── v2: 32px 지형 텍스처 (2x2 타일에 걸쳐 반복) ──
  g_grass: { size: 32, fill: 'grass', pattern: 'patches', cell: 10, dark: 'grassS', light: 'grassL', darker: 'grassD', t0: 0.22, t1: 0.4, t2: 0.66, noise: [['grassL', 0.05], ['grassS', 0.06]], sprinkle: [{ shape: 'blade', color: 'grassL', shade: 'grassS', count: 10 }] },
  g_moss: { size: 32, fill: 'moss', pattern: 'patches', cell: 10, dark: 'mossS', light: 'mossL', darker: 'grassDD', t0: 0.24, t1: 0.42, t2: 0.7, noise: [['mossS', 0.06]], sprinkle: [{ shape: 'blade', color: 'mossL', shade: 'mossS', count: 8 }] },
  g_flower: { size: 32, base: 'g_grass', sprinkle: [{ shape: 'blade', color: 'grassL', shade: 'grassS', count: 6 }, { shape: 'flower', color: 'flowerPink', count: 4 }, { shape: 'flower', color: 'flowerWhite', count: 3 }, { shape: 'flower', color: 'flowerYellow', count: 2 }, { shape: 'flower', color: 'flowerBlue', count: 2 }] },
  g_dirt: { size: 32, fill: 'dirt', pattern: 'patches', cell: 8, dark: 'dirtS', light: 'dirtL', t1: 0.35, t2: 0.7, noise: [['dirtS', 0.05]], sprinkle: [{ shape: 'pebble', color: 'stoneL', shade: 'stoneS', count: 5 }] },
  g_sand: { size: 32, fill: 'sand', pattern: 'patches', cell: 8, dark: 'sandS', light: 'sandL', t1: 0.3, t2: 0.72, noise: [['sandS', 0.04], ['white', 0.02]] },
  g_bed: { size: 32, fill: 'riverbed', pattern: 'patches', cell: 6, dark: 'earthS', light: 'stone', noise: [['stoneS', 0.08]], sprinkle: [{ shape: 'pebble', color: 'stoneL', shade: 'stoneS', count: 8 }] },
  cliff: { size: 32, fill: 'earth', pattern: 'strata', bands: ['earth', 'earthS', 'earthL', 'earthS', 'earth', 'earthD'], bandH: 5, stones: 7, stone: 'stone', stoneL: 'stoneL', stoneS: 'stoneD', lip: 4, lipColors: ['grass', 'grassS', 'grassDD'] },
  cliffSand: { size: 32, base: 'cliff', lipColors: ['sand', 'sandS', 'earthS'] },
  cliffCave: { size: 32, fill: 'caveRock', pattern: 'strata', bands: ['caveRock', 'caveRockS', 'caveRockL', 'caveRockS'], bandH: 6, stones: 6, stone: 'caveRockL', stoneL: 'crystalS', stoneS: 'caveRockS', lip: 0 },
  stoneTop: { size: 32, fill: 'stone', pattern: 'patches', cell: 8, dark: 'stoneS', light: 'stoneL', noise: [['moss', 0.04]] },
  leaves2: { size: 32, fill: 'green', pattern: 'patches', cell: 6, dark: 'greenS', light: 'greenL', darker: 'grassD', t0: 0.25, t1: 0.42, t2: 0.62, noise: [['mossL', 0.04]] },
  pineTex: { size: 32, fill: 'pine', pattern: 'patches', cell: 5, dark: 'pineS', light: 'pineL', darker: 'pineD', t0: 0.25, t1: 0.42, t2: 0.7 },
  barkTex: { size: 32, fill: 'wood', pattern: 'vstripes', line: 'woodS', noise: [['earthD', 0.1], ['woodL', 0.06]] },
  stoneFloor2: { size: 32, fill: 'stone', pattern: 'cobble', stones: 13, mortar: 'stoneD', shade: 'stoneS', hi: 'stoneL', shades: ['stone', 'stoneL', 'stone', 'stoneS'], noise: [['stoneS', 0.05], ['moss', 0.02]] },
  planks2: { size: 32, fill: 'wood', pattern: 'planks', ph: 8, line: 'woodS', shades: ['wood', 'woodL', 'wood', 'earthL'], noise: [['woodS', 0.05]] },
  caveFloor2: { size: 32, fill: 'caveRock', pattern: 'patches', cell: 8, dark: 'caveRockS', light: 'caveRockL', noise: [['caveRockS', 0.06]], sprinkle: [{ shape: 'pebble', color: 'caveRockL', shade: 'caveRockS', count: 6 }, { shape: 'speck', color: 'crystal', count: 3 }] },
  altar2: { size: 32, fill: 'stoneL', pattern: 'tiles', cell: 16, mortar: 'stoneS', shades: ['stoneL', 'stone'], sprinkle: [{ shape: 'rune', color: 'crystal', count: 1 }] },
  tuft: { size: 16, fill: 'none', pattern: 'tuft', blades: 9, colors: ['grassS', 'grass', 'grassL'] },
  tuftDark: { size: 16, fill: 'none', pattern: 'tuft', blades: 10, colors: ['mossS', 'moss', 'mossL'] },
  tuftFlower: { size: 16, fill: 'none', pattern: 'tuft', blades: 6, flowers: 3, colors: ['grassS', 'grass', 'grassL'], flowerColors: ['flowerPink', 'flowerWhite', 'flowerBlue', 'flowerYellow'] },
  tuftCave: { size: 16, fill: 'none', pattern: 'tuft', blades: 5, colors: ['caveRockS', 'crystalS', 'crystal'] },
  crate: { size: 16, fill: 'woodL', pattern: 'planks', ph: 4, line: 'woodS', shades: ['woodL', 'wood'] },
  plaster2: { size: 32, fill: 'plaster', pattern: 'patches', cell: 8, dark: 'plasterS', light: 'cream', t1: 0.25, t2: 0.8 },
};
