"""Hand-pixelled 16x16 UI icons from ASCII maps -> public/assets/ui/icons.png/json"""
import json
import os

import numpy as np
from PIL import Image

from sdf import hex2rgb

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "public", "assets", "ui")

PAL = {
    ".": None,
    "k": "#120c18", "K": "#2a2236",
    "w": "#ffffff", "W": "#d8e4f4", "s": "#9aaccc", "S": "#5a6c90",
    "y": "#fff0a0", "Y": "#f0c040", "o": "#c07a20", "O": "#7a4410",
    "r": "#ff8a7a", "R": "#e0303a", "d": "#8a1020",
    "b": "#a8e0ff", "B": "#40a0f0", "n": "#1a4a9a",
    "g": "#b0ffb0", "G": "#40c060", "e": "#1a6a3a",
    "p": "#f0b0ff", "P": "#a050d0", "q": "#4a1a70",
    "c": "#a0ffff", "C": "#30c0d0", "t": "#a07040", "T": "#5a3418",
}

ICONS = {
    "attack": """
................
.............ww.
............wWs.
...........wWs..
..........wWs...
.........wWs....
........wWs.....
.......wWs......
..oY..wWs.......
..YyYwWs........
...YyWs.........
...OYyY.........
..tTO.YY........
.tTk...O........
.Tk.............
................""",
    "skill": """
................
.......y........
.......Y........
......yYy.......
...y..YwY..y....
....Y.ywy.Y.....
.....yywyy......
.yYYYywwwyYYYy..
.....yywyy......
....Y.ywy.Y.....
...y..YwY..y....
......yYy.......
.......Y........
.......y........
................
................""",
    "echo": """
................
.......w........
......wbB.......
.....wbbBn......
....wbbBBnn.....
....bbbBBnn.....
...wbbBBBnnn....
...bbbBBBnnn....
...bbBBBBnnn....
....bBBBBnn.....
....BBBBnnn.....
.....BBBnn......
......Bnn.......
.......n........
................
................""",
    "guard": """
................
...KKKKKKKKKK...
..KWWWWWWWWssK..
..KWwwwYYwwssK..
..KWwwwYYwwssK..
..KWYYYYYYYYsK..
..KWYYYYYYYYsK..
..KWwwwYYwwssK..
...KWwwYYwssK...
...KWwwYYwssK...
....KWwYYssK....
.....KWYYsK.....
......KWsK......
.......KK.......
................
................""",
    "item": """
................
......kkkk......
......kWWk......
.......kk.......
......kbbk......
.....kbwbBk.....
....kbwbbBBk....
....kbbbBBnk....
....kBBBBBnk....
....kBBBBnnk....
.....kBBnnk.....
......kkkk......
................
................
................
................""",
    "run": """
................
................
.........kk.....
........kWWk....
........kWWk....
.......kSsk.....
....kkkSssk.....
...kWWkSsskk....
...kkk.kSssWk...
.......kSkkWk...
......kSk..k....
.....kSk........
....kSSkk.......
....kkkk........
................
................""",
    "resonance": """
.......y........
.......Y........
...y...Y...y....
....Y..Y..Y.....
.....YyyyY......
..y..ywwwy..y...
...YYywwwyYY....
yYYYywwwwwyYYYy.
...YYywwwyYY....
..y..ywwwy..y...
.....YyyyY......
....Y..Y..Y.....
...y...Y...y....
.......Y........
.......y........
................""",
    "fire": """
................
.......r........
......rR........
......RRr.......
.....rRRR..r....
....rRRyRr.rR...
....RRyyRRrRR...
...rRyyyyRRRR...
...RRywwyyRRd...
...RRywwwyRRd...
...dRyywyyRd....
....dRRyyRRd....
.....ddRRdd.....
................
................
................""",
    "ice": """
................
.......w........
.......b........
...w...b...w....
....b..b..b.....
.....bBbBb......
.......B........
.wbbbBBwBBbbbw..
.......B........
.....bBbBb......
....b..b..b.....
...w...b...w....
.......b........
.......w........
................
................""",
    "thunder": """
................
........pw......
.......pP.......
......pPP.......
.....pPP........
....pPPPPPp.....
.......PPp......
......pPp.......
.....pPp........
....pPp.........
...pPp..........
...Pp...........
..pp............
................
................
................""",
    "light": """
................
.......w........
.......y........
...w..yYy..w....
....y.YwY.y.....
.....YwwwY......
...yYwwwwwYy....
.wyYwwwwwwwYyw..
...yYwwwwwYy....
.....YwwwY......
....y.YwY.y.....
...w..yYy..w....
.......y........
.......w........
................
................""",
    "dark": """
................
......qqqq......
....qqPPPPqq....
...qPPpppPPPq...
...qPp..qpPPq...
..qPp....qPPPq..
..qPp.....qPPq..
..qPPq....qPPq..
..qPPPq..qPPPq..
...qPPPqqPPPq...
...qqPPPPPPqq...
....qqqPPqqq....
......qqqq......
................
................
................""",
    "heal": """
................
......kkkk......
......kggk......
......kGGk......
......kGGk......
..kkkkkGGkkkkk..
..kgGGGGGGGGek..
..kgGGGGGGGGek..
..kkkkkGGkkkkk..
......kGGk......
......kGGk......
......kGek......
......kkkk......
................
................
................""",
    "cursor": """
................
................
................
.kk.............
.kWkk...........
.kWWWkk.........
.kWwwWWkk.......
.kWwwwwWWkk.....
.kWwwwwwwWWk....
.kWwwwwwwWWk....
.kWwwwwWWkk.....
.kWwwWWkk.......
.kWWWkk.........
.kWkk...........
.kk.............
................""",
    "down": """
................
................
..kkkkkkkkkkkk..
..kYYYYYYYYYYk..
...kYyyyyyyYk...
...kYyyyyyyYk...
....kYyyyyYk....
....kYyyyyYk....
.....kYyyYk.....
.....kYyyYk.....
......kYYk......
......kYYk......
.......kk.......
................
................
................""",
    "gil": """
................
.....kkkkkk.....
....kYYYYYYk....
...kYyyyyyYOk...
..kYyyYYYyyYOk..
..kYyY.YYYyYOk..
..kYyY..YYyYOk..
..kYyYY..YyYOk..
..kYyyYYYyyYOk..
...kYyyyyyYOk...
....kOOOOOOk....
.....kkkkkk.....
................
................
................
................""",
}


def build():
    os.makedirs(OUT, exist_ok=True)
    names = list(ICONS)
    S = 16
    atlas = np.zeros((S, S * len(names), 4), dtype=np.uint8)
    meta = {"image": "icons.png", "size": S, "icons": {}}
    for i, n in enumerate(names):
        rows = [r for r in ICONS[n].strip("\n").split("\n")]
        for y, row in enumerate(rows[:S]):
            for x, ch in enumerate(row[:S]):
                c = PAL.get(ch)
                if c:
                    r, g, b = hex2rgb(c)
                    atlas[y, i * S + x] = [int(r * 255), int(g * 255), int(b * 255), 255]
        meta["icons"][n] = i
    # add a dark outline around every icon for readability
    a = atlas[..., 3] > 0
    out = atlas.copy()
    for dy, dx in ((0, 1), (0, -1), (1, 0), (-1, 0)):
        nb = np.roll(np.roll(a, dy, 0), dx, 1)
        edge = nb & ~a
        out[edge] = [18, 12, 24, 255]
    Image.fromarray(out, "RGBA").save(os.path.join(OUT, "icons.png"))
    json.dump(meta, open(os.path.join(OUT, "icons.json"), "w"))
    Image.fromarray(out, "RGBA").resize((S * len(names) * 4, S * 4), Image.NEAREST).save("/tmp/claude-0/-home-user-jy2910/5a38f85b-c21f-5751-aafd-449cad322cff/scratchpad/icons.png")
    print("icons", len(names))


if __name__ == "__main__":
    build()
